export function exportCSV(snapshotHistory, scenarioName) {
  if (!snapshotHistory?.length) return

  const headers = [
    'Year','World GDP (T)','Population (M)','Temp Anomaly (°C)',
    'CO2 (ppm)','Automation (%)','Renewables (%)','Unemployment (%)',
    'Gini','Sea Level (cm)','Geo Stability',
  ]

  const rows = snapshotHistory.map((s) => [
    Math.floor(s.year),
    s.world_gdp?.toFixed(2),
    s.population?.toFixed(0),
    s.temp_anomaly?.toFixed(3),
    s.co2_ppm?.toFixed(1),
    ((s.automation_index||0)*100).toFixed(1),
    ((s.renewable_share||0)*100).toFixed(1),
    ((s.unemployment_rate||0)*100).toFixed(2),
    s.gini_coefficient?.toFixed(3),
    s.sea_level_rise_cm?.toFixed(2),
    s.geopolitical_stability?.toFixed(3),
  ])

  const csv = [headers, ...rows].map((r) => r.join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `AICS_${scenarioName.replace(/\s+/g,'_')}_${Date.now()}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

export function exportPDF(snapshotHistory, scenarioName, snapshot) {
  const last = snapshotHistory.slice(-1)[0] || snapshot
  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>AICS Report — ${scenarioName}</title>
<style>
  body { font-family: 'Segoe UI',sans-serif; background:#0a0a0f; color:#f1f0ff; margin:0; padding:40px; }
  h1   { font-size:32px; font-weight:800; margin-bottom:4px; }
  .sub { font-size:12px; color:#a78bfa; letter-spacing:3px; margin-bottom:32px; font-family:monospace; }
  .grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:32px; }
  .card { background:#13131e; border:1px solid rgba(124,58,237,0.25); border-radius:12px; padding:20px; }
  .card-label { font-size:10px; color:rgba(241,240,255,0.4); letter-spacing:2px; text-transform:uppercase; margin-bottom:8px; font-family:monospace; }
  .card-value { font-size:24px; font-weight:700; color:#a78bfa; font-family:monospace; }
  table { width:100%; border-collapse:collapse; font-family:monospace; font-size:12px; }
  th    { text-align:left; padding:10px 14px; font-size:10px; color:rgba(241,240,255,0.4); letter-spacing:2px; border-bottom:1px solid rgba(124,58,237,0.15); }
  td    { padding:10px 14px; border-bottom:1px solid rgba(124,58,237,0.06); }
  .footer { margin-top:40px; font-size:11px; color:rgba(241,240,255,0.3); font-family:monospace; }
</style>
</head>
<body>
  <h1>AICS Simulation Report</h1>
  <p class="sub">SCENARIO: ${scenarioName.toUpperCase()} &nbsp;·&nbsp; GENERATED ${new Date().toLocaleDateString()}</p>

  <div class="grid">
    <div class="card"><div class="card-label">Final Year</div><div class="card-value">${Math.floor(last?.year||2025)}</div></div>
    <div class="card"><div class="card-label">World GDP</div><div class="card-value">$${(last?.world_gdp||0).toFixed(1)}T</div></div>
    <div class="card"><div class="card-label">Population</div><div class="card-value">${((last?.population||8100)/1000).toFixed(2)}B</div></div>
    <div class="card"><div class="card-label">Temp Anomaly</div><div class="card-value">+${(last?.temp_anomaly||1.2).toFixed(2)}°C</div></div>
    <div class="card"><div class="card-label">CO₂ Level</div><div class="card-value">${(last?.co2_ppm||422).toFixed(0)} ppm</div></div>
    <div class="card"><div class="card-label">Automation</div><div class="card-value">${((last?.automation_index||0)*100).toFixed(0)}%</div></div>
  </div>

  <table>
    <tr>${['Year','GDP ($T)','Temp (°C)','CO₂','Automation','Renewables','Unemployment'].map(h=>`<th>${h}</th>`).join('')}</tr>
    ${snapshotHistory.filter((_,i)=>i%4===0).slice(-30).map((s)=>`
    <tr>
      <td>${Math.floor(s.year)}</td>
      <td>$${(s.world_gdp||0).toFixed(1)}T</td>
      <td>+${(s.temp_anomaly||0).toFixed(2)}°C</td>
      <td>${(s.co2_ppm||0).toFixed(0)}</td>
      <td>${((s.automation_index||0)*100).toFixed(0)}%</td>
      <td>${((s.renewable_share||0)*100).toFixed(0)}%</td>
      <td>${((s.unemployment_rate||0)*100).toFixed(1)}%</td>
    </tr>`).join('')}
  </table>

  <p class="footer">Generated by AI Civilization Simulator v1.0 · ${new Date().toISOString()}</p>
</body>
</html>`

  const w = window.open('', '_blank')
  w.document.write(html)
  w.document.close()
  setTimeout(() => w.print(), 500)
}